### ISSUE TITLE
Dúvida ao adicionar classes para os times

### ISSUE THREAD

**Issue by hevertonsb** [schoolofnetcom/vue2#1]
Como eu poderia adicionar classes a certos itens da lista? 
Queria por exemplo adicionar uma classe aos quatro primeiros times, outra classe aos últimos quatro times e aos quinto e sexto uma nova classe, como no código abaixo. Fiz usando jquery assim:

$('#tabela tbody tr:lt(4)').addClass('success');
$('#tabela tbody tr:eq(4)').addClass('warning');
$('#tabela tbody tr:eq(5)').addClass('warning');
$('#tabela tbody tr:gt(15)').addClass('danger');

Mas ao inserir um jogo e voltando para a tabela, elas perdem essas classes. 
Como devo fazer? Já que usamos um loop para criar esses itens.
Agradeço desde já.

**Comment by argentinaluiz** [comment]
Olá @hevertonsb,

No curso de Vue.js com Autenticação, fizemos isto. Trabalhamos com property-binding no atributo class, exemplo:
```html
<tr v-for="(time,index) in timesFiltered" :class="{'success': index < 3, 'warning': index > 2 && index <6, 'danger': index > 15}">
```

**Comment by hevertonsb** [comment]
Muito obrigado @argentinaluiz, com certeza irei assinar e fazer outros cursos, o de Vue.js foi o primeiro que consegui ir até o final. Última pergunta, para subir o projeto para um servidor online, basta subir os arquivos para o diretório do meu interesse? Deu erro no caminho do build.js, coloquei link absoluto temporariamente. Grande abraço e obrigado novamente!
